pipeline:
  projectIdentifier: Ruchira_Project
  orgIdentifier: CI
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: mvn clean install -DskipTests
              - step:
                  type: Run
                  name: unit test
                  identifier: unit_test
                  spec:
                    shell: Sh
                    command: mvn test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                  when:
                    stageStatus: Success
                    condition: "false"
              - step:
                  type: Test
                  name: Test_1
                  identifier: Test_1
                  spec:
                    shell: Sh
                    command: mvn tests
                    intelligenceMode: true
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: ruchira_docker
                    repo: ruchirabajaj/harness-ci
                    tags:
                      - <+pipeline.sequenceID>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: ruchira
        repoName: jhttp
        build: <+input>
  identifier: Ruchira_Lab2
  tags: {}
  name: Ruchira_Lab2
