pipeline:
  projectIdentifier: Ruchira_Project
  orgIdentifier: CI
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: package
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: mvn clean install -DskipTests
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      docker build -t test123cloud:test-<+pipeline.sequenceId> .
                      docker images
              - step:
                  type: AquaTrivy
                  name: AquaTrivy_1
                  identifier: AquaTrivy_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    image:
                      type: docker_v2
                      tag: <+pipeline.sequenceId>
                      name: ruchirabajaj/harness-ci
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: ruchira
        repoName: jhttp
        build: <+input>
  tags: {}
  identifier: Ruchira_Lab7
  name: Ruchira_Lab7
